# Generated by Django 2.1.5 on 2019-02-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizportal', '0003_auto_20190204_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='id_no',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
