# Generated by Django 2.1.5 on 2019-02-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizportal', '0004_auto_20190204_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedq',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
