# Generated by Django 2.1.5 on 2019-02-18 21:05

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizportal', '0005_solvedq_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section1',
            fields=[
                ('id_no', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('optionA', models.TextField()),
                ('optionB', models.TextField()),
                ('optionC', models.TextField()),
                ('optionD', models.TextField()),
                ('correct_choice', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section2',
            fields=[
                ('id_no', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('optionA', models.TextField()),
                ('optionB', models.TextField()),
                ('optionC', models.TextField()),
                ('optionD', models.TextField()),
                ('correct_choice', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section3',
            fields=[
                ('id_no', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('optionA', models.TextField()),
                ('optionB', models.TextField()),
                ('optionC', models.TextField()),
                ('optionD', models.TextField()),
                ('correct_choice', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SolvedQ1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_idsol', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('q_idunsol', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('id_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolvedQ2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_idsol', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('q_idunsol', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('id_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolvedQ3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_idsol', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('q_idunsol', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('id_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Time1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, max_length=100)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Time2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, max_length=100)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Time3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, max_length=100)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='solvedq',
            name='id_no',
        ),
        migrations.RemoveField(
            model_name='solvedq',
            name='q_id',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.DeleteModel(
            name='QuestionData',
        ),
        migrations.DeleteModel(
            name='SolvedQ',
        ),
    ]
