# Generated by Django 2.1.5 on 2019-02-19 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizportal', '0007_auto_20190219_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvedq1',
            name='q_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizportal.Section1'),
        ),
        migrations.AlterField(
            model_name='solvedq2',
            name='q_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizportal.Section2'),
        ),
        migrations.AlterField(
            model_name='solvedq3',
            name='q_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizportal.Section3'),
        ),
    ]
