# Generated by Django 2.1.5 on 2019-02-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizportal', '0009_auto_20190227_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(default=20)),
                ('time', models.TimeField()),
            ],
        ),
    ]
