# Generated by Django 2.1.5 on 2019-02-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizportal', '0010_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='s_no',
            field=models.IntegerField(),
        ),
    ]
