# Generated by Django 2.1.5 on 2019-02-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizportal', '0011_auto_20190228_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='s_no',
            field=models.PositiveIntegerField(),
        ),
    ]
