# Generated by Django 2.1.5 on 2019-03-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizportal', '0013_section3_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section3',
            name='image',
            field=models.ImageField(blank=True, upload_to='pictures'),
        ),
    ]
